# Generated by Django 3.2.4 on 2021-07-02 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('detail', models.TextField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(blank=True, choices=[('W', 'waiting for delivery'), ('S', 'Shipped '), ('C', 'Cancel')], max_length=5, null=True)),
                ('iv_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('detail', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('is_enabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapi.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('img_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='shopapi.product')),
            ],
            options={
                'verbose_name_plural': 'Product Image',
            },
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopapi.invoice')),
                ('iv_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('cart_product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='shopapi.product')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'unique_together': {('cart_product', 'user')},
            },
        ),
    ]
